### ISSUE TITLE
yaml couldn't been found when using alauda's CLI in ubuntu  64-bit(14.04)

### ISSUE THREAD

**Issue by ranglang** [alaudacloud/alauda-CLI#1]
when i  try to log into alauda, it says "ImportError: No module named yaml",fix it by running ```pip install pyyaml```,I'm wondering if it might be better to update the doc.
```
# alauda
Traceback (most recent call last):
  File "/usr/local/bin/alauda", line 7, in <module>
    from alaudacli.alauda_cli import main
  File "/usr/local/lib/python2.7/dist-packages/alaudacli/alauda_cli.py", line 5, in <module>
    import cmd_processor
  File "/usr/local/lib/python2.7/dist-packages/alaudacli/cmd_processor.py", line 1, in <module>
    from . import commands
  File "/usr/local/lib/python2.7/dist-packages/alaudacli/commands.py", line 7, in <module>
    import compose
  File "/usr/local/lib/python2.7/dist-packages/alaudacli/compose.py", line 1, in <module>
    import yaml
ImportError: No module named yaml

```

**Comment by alaudatest** [comment]
@ranglang I think this will not show up at version 0.2.2. Thanks. I will upgrade the doc
