### ISSUE TITLE
[alauda server error] 500

### ISSUE THREAD

**Issue by fxf601244325** [alaudacloud/alauda-CLI#6]
[alauda] Creating and starting service "hello"
[alauda server error] 500 {"errors": [{"code": "unknown_issue", "message": "'NoneType' object has no attribute 'startswith'", "type": "server_error"}]}
Traceback (most recent call last):
  File "build/bdist.macosx-10.11-x86_64/egg/alaudacli/alauda_cli.py", line 45, in main
    cmd_processor.process_cmds(args)
  File "build/bdist.macosx-10.11-x86_64/egg/alaudacli/cmd_processor.py", line 19, in process_cmds
    scaling_info=(args.autoscale, args.autoscaling_config), custom_domain_name=args.domain, region_name=args.region)
  File "build/bdist.macosx-10.11-x86_64/egg/alaudacli/commands.py", line 66, in service_create
    service.run()
  File "build/bdist.macosx-10.11-x86_64/egg/alaudacli/service.py", line 160, in run
    self._create_remote('STARTED')
  File "build/bdist.macosx-10.11-x86_64/egg/alaudacli/service.py", line 102, in _create_remote
    util.check_response(r)
  File "build/bdist.macosx-10.11-x86_64/egg/alaudacli/util.py", line 257, in check_response
    raise AlaudaServerError(response.status_code, response.text)
AlaudaServerError: [alauda server error] 500 {"errors": [{"code": "unknown_issue", "message": "'NoneType' object has no attribute 'startswith'", "type": "server_error"}]}

**Comment by alaudatest** [comment]
Sorry about that. Please spec `-re` when you create a service. Optional value is `BEIJING1`, `HONGKONG1`,`SHANGHAI1`,`BEIJING2`
